### ISSUE TITLE
Can't remove items from cauldron.

### ISSUE THREAD

**Issue by V1cti0N** [AdamCvijanovic/Herding-Ghosts-Unity#103]
**Describe the bug**
- Players are unable to take out items from the cauldron once placed.

**Version**
- Herding Ghosts V0.06

**To Reproduce**
1. Place items in cauldron.
2. Try to take items out of cauldron once placed

**Expected behavior**
Player should be able to take out items. Important if player has placed items in the wrong order.

**Screenshots**

**Desktop System (please complete the following information):**
- OS: Windows 10

**Additional context**
- @SparkyAlduin is currently working on a purge lever that should fix this issue.

**Comment by AdamCvijanovic** [comment]
added purge lever
