### ISSUE TITLE
Stun Timer & Frantic Movement on Granddaughter 

### ISSUE THREAD

**Issue by SparkyAlduin** [AdamCvijanovic/Herding-Ghosts-Unity#32]
Currently, there isn't feedback from the Granddaughter getting scared by a ghost.

It would be more logical and impactful to have a response from the Granddaughter getting scared. This will visually notify the players and make the Granddaughter have personality. 

Impact:

- Granddaughter gets scared and is stunned - Dog Ghost?
- Granddaughter is scared and runs frantically around in a spot -Calcifer? 
- Granddaughter gets scared and may potentially forget a task, reducing the task progression - This is just a potential idea.

Note:

- After getting scared the Granddaughter should be invincible for a few short moments to not allows ghosts to just constantly stack fear on her

**Comment by V1cti0N** [comment]
Not important for now/Requires other game enhancements before we can implement.
